=== katarziz/MolSim/input/input.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Molsim_Input">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Parameters">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="delta_t" default="0.0002" type="xs:decimal"  />
                            <xs:element name="t_end" type="xs:decimal" default="5.0"/>
                            <xs:element name="grav" type="xs:decimal" default="-9.81"/>
                            <xs:element name="container" type="xs:string" default="LinkedCell"/>
                            <xs:element name="checkpoint_freq" type="xs:int" default="0"/>
                            <xs:element name="box_size">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="x-size" type="xs:decimal"  default="3.0"/>
                                        <xs:element name="y-size" type="xs:decimal"  default="3.0"/>
                                        <xs:element name="z-size" type="xs:decimal"  default="0.0"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="boundary_conditions">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="top_bound" type="xs:string" default="out"/>
                                        <xs:element name="right_bound" type="xs:string" default="out" />
                                        <xs:element name="bottom_bound" type="xs:string" default="out"/>
                                        <xs:element name="left_bound" type="xs:string" default="out"/>
                                        <xs:element name="front_bound" type="xs:string" default="out"/>
                                        <xs:element name="back_bound" type="xs:string" default="out"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="cutoff" type="xs:decimal" default="3.0"/>
                            <xs:element name="writer" type="xs:string" default="vtk"/>
                            <xs:element name="force" type="xs:string" default="lennard-jones"/>
                            <xs:element name="output_name" type="xs:string" default="MD_vtk"/>
                            <xs:element name="output_frequency" type="xs:integer" default="50"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="ThermostatParams">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="T_init" type="xs:decimal" default="0.0"/>
                            <xs:element name="T_targ" type="xs:decimal" default="-1.0"/>
                            <xs:element name="f_therm" type="xs:integer" default="5"/>
                            <xs:element name="delta_T" type="xs:double" default="0.0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="Particles">
                    <xs:complexType>
                        <xs:sequence maxOccurs="unbounded">
                            <xs:element name="cuboid" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="base_coordinates">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="x-coordinate" type="xs:decimal"/>
                                                    <xs:element name="y-coordinate" type="xs:decimal"/>
                                                    <xs:element name="z-coordinate" type="xs:decimal"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="number_particles">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="x-number" type="xs:integer"/>
                                                    <xs:element name="y-number" type="xs:integer"/>
                                                    <xs:element name="z-number" type="xs:integer"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="velocity">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="x-velocity" type="xs:decimal"/>
                                                    <xs:element name="y-velocity" type="xs:decimal"/>
                                                    <xs:element name="z-velocity" type="xs:decimal"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="spacing" type="xs:decimal"/>
                                        <xs:element name="mass" type="xs:decimal"/>
                                        <xs:element name="type" type="xs:integer" default="0"/>
                                        <xs:element name="eps" type="xs:decimal"/>
                                        <xs:element name="sigma" type="xs:decimal"/>
                                        <xs:element name="fixed" type="xs:boolean"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="particle" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="position">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="x-coordinate" type="xs:decimal"/>
                                                    <xs:element name="y-coordinate" type="xs:decimal"/>
                                                    <xs:element name="z-coordinate" type="xs:decimal"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="velocity">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="x-velocity" type="xs:decimal"/>
                                                    <xs:element name="y-velocity" type="xs:decimal"/>
                                                    <xs:element name="z-velocity" type="xs:decimal"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="mass" type="xs:decimal"/>
                                        <xs:element name="type" type="xs:integer" default="0"/>
                                        <xs:element name="eps" type="xs:decimal"/>
                                        <xs:element name="sigma" type="xs:decimal"/>
                                        <xs:element name="fixed" type="xs:boolean"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="disc" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="position">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="x-coordinate" type="xs:decimal"/>
                                                    <xs:element name="y-coordinate" type="xs:decimal"/>
                                                    <xs:element name="z-coordinate" type="xs:decimal"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="velocity">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="x-velocity" type="xs:decimal"/>
                                                    <xs:element name="y-velocity" type="xs:decimal"/>
                                                    <xs:element name="z-velocity" type="xs:decimal"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="radius" type="xs:integer"/>
                                        <xs:element name="mass" type="xs:decimal"/>
                                        <xs:element name="type" type="xs:integer" default="0"/>
                                        <xs:element name="eps" type="xs:decimal"/>
                                        <xs:element name="sigma" type="xs:decimal"/>
                                        <xs:element name="fixed" type="xs:boolean"/>
                                        <xs:element name="spacing" type="xs:decimal"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="checkpoint" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="checkpoint_file" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="membrane" minOccurs="0" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="base_coordinates">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="x-coordinate" type="xs:decimal"/>
                                                    <xs:element name="y-coordinate" type="xs:decimal"/>
                                                    <xs:element name="z-coordinate" type="xs:decimal"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                       <xs:element name="plane" type="xs:string"/>
                                        <xs:element name="number_particles">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="width" type="xs:integer"/>
                                                    <xs:element name="height" type="xs:integer"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="velocity">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="x-velocity" type="xs:decimal"/>
                                                    <xs:element name="y-velocity" type="xs:decimal"/>
                                                    <xs:element name="z-velocity" type="xs:decimal"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="spacing" type="xs:decimal"/>
                                        <xs:element name="mass" type="xs:decimal"/>
                                        <xs:element name="type" type="xs:integer" default="0"/>
                                        <xs:element name="eps" type="xs:decimal"/>
                                        <xs:element name="sigma" type="xs:decimal"/>
                                        <xs:element name="r_zero" type="xs:double"/>
                                        <xs:element name="k" type="xs:double"/>
                                        <xs:element name="F_up" type="xs:double"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== katarziz/MolSim/input/speedup.xml
<?xml version="1.0" encoding="UTF-8"?>

<Molsim_Input xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="input.xsd">
    <Parameters>
        <delta_t>0.0005</delta_t>
        <t_end>10</t_end>
        <grav>-12.44</grav>
        <container>LinkedCell</container>
        <checkpoint_freq>1000000</checkpoint_freq>
        <box_size>
            <x-size>60</x-size>
            <y-size>60</y-size>
            <z-size>60</z-size>
        </box_size>
        <boundary_conditions>
            <top_bound>ref</top_bound>
            <right_bound>per</right_bound>
            <bottom_bound>ref</bottom_bound>
            <left_bound>per</left_bound>
            <front_bound>per</front_bound>
            <back_bound>per</back_bound>
        </boundary_conditions>
        <cutoff>3.6</cutoff>
        <writer/>
        <force/>
        <output_name>speedup</output_name>
        <output_frequency>1000000</output_frequency>
        <statistics_freq>1000000</statistics_freq>
    </Parameters>
    <ThermostatParams>
        <T_init>40</T_init>
        <T_targ>40</T_targ>
        <f_therm>1000</f_therm>
        <delta_T>INF</delta_T>
    </ThermostatParams>
    <Particles>
        <cuboid>
            <base_coordinates>
                <x-coordinate>0.6</x-coordinate>
                <y-coordinate>0.6</y-coordinate>
                <z-coordinate>0.6</z-coordinate>
            </base_coordinates>
            <number_particles>
                <x-number>50</x-number>
                <y-number>20</y-number>
                <z-number>50</z-number>
            </number_particles>
            <velocity>
                <x-velocity>0.0</x-velocity>
                <y-velocity>0.0</y-velocity>
                <z-velocity>0.0</z-velocity>
            </velocity>
            <spacing>1.2</spacing>
            <mass>1.0</mass>
            <type>0</type>
            <eps>1.0</eps>
            <sigma>1.2</sigma>
            <fixed>false</fixed>
        </cuboid>
        <cuboid>
            <base_coordinates>
                <x-coordinate>0.6</x-coordinate>
                <y-coordinate>24.6</y-coordinate>
                <z-coordinate>0.6</z-coordinate>
            </base_coordinates>
            <number_particles>
                <x-number>50</x-number>
                <y-number>20</y-number>
                <z-number>50</z-number>
            </number_particles>
            <velocity>
                <x-velocity>0.0</x-velocity>
                <y-velocity>0.0</y-velocity>
                <z-velocity>0.0</z-velocity>
            </velocity>
            <spacing>1.2</spacing>
            <mass>2.0</mass>
            <type>1</type>
            <eps>1.0</eps>
            <sigma>1.1</sigma>
            <fixed>false</fixed>
        </cuboid>
    </Particles>
</Molsim_Input>

=== katarziz/MolSim/input/RaindropInput.xml
<?xml version="1.0" encoding="UTF-8"?>

<Molsim_Input xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="input.xsd">
    <Parameters>
        <delta_t>0.00005</delta_t>
        <t_end>10.0</t_end>
        <box_size>
            <x-size/>
            <y-size/>
            <z-size/>
        </box_size>
        <number_cells>
            <x-number>120</x-number>
            <y-number>50</y-number>
            <z-number>1</z-number>
        </number_cells>
        <boundary_conditions>
            <top_bound/>
            <right_bound/>
            <bottom_bound>ref</bottom_bound>
            <left_bound/>
        </boundary_conditions>
        <cutoff>3.0</cutoff>
        <writer/>
        <force/>
        <output_name>raindrop</output_name>
        <output_frequency/>
    </Parameters>
    <Particles>
        <disc>
            <position>
                <x-coordinate>60.0</x-coordinate>
                <y-coordinate>25.0</y-coordinate>
                <z-coordinate>0.0</z-coordinate>
            </position>
            <velocity>
                <x-velocity>0.0</x-velocity>
                <y-velocity>-10.0</y-velocity>
                <z-velocity>0.0</z-velocity>
            </velocity>
            <radius>15</radius>
            <mass>1.0</mass>
            <spacing>1.1225</spacing>
            <brownian_vel>0.0</brownian_vel>
        </disc>
    </Particles>
</Molsim_Input>

=== katarziz/MolSim/input/benchy.xml
<?xml version="1.0" encoding="UTF-8"?>

<Molsim_Input xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="input.xsd">
    <Parameters>
        <delta_t>0.0005</delta_t>
        <t_end>0.5</t_end>
        <grav>-12.44</grav>
        <container>LinkedCell</container>
        <checkpoint_freq/>
        <box_size>
            <x-size>300</x-size>
            <y-size>54</y-size>
            <z-size>0</z-size>
        </box_size>
        <boundary_conditions>
            <top_bound>ref</top_bound>
            <right_bound>per</right_bound>
            <bottom_bound>ref</bottom_bound>
            <left_bound>per</left_bound>
            <front_bound>ref</front_bound>
            <back_bound>ref</back_bound>
        </boundary_conditions>
        <cutoff>3.0</cutoff>
        <writer/>
        <force/>
        <output_name>benchy</output_name>
        <output_frequency>2000</output_frequency>
    </Parameters>
    <ThermostatParams>
        <T_init>40</T_init>
        <T_targ>40</T_targ>
        <f_therm>1000</f_therm>
        <delta_T>INF</delta_T>
    </ThermostatParams>
    <Particles>
        <cuboid>
            <base_coordinates>
                <x-coordinate>0.6</x-coordinate>
                <y-coordinate>2.0</y-coordinate>
                <z-coordinate>0.0</z-coordinate>
            </base_coordinates>
            <number_particles>
                <x-number>250</x-number>
                <y-number>20</y-number>
                <z-number>1</z-number>
            </number_particles>
            <velocity>
                <x-velocity>0.0</x-velocity>
                <y-velocity>0.0</y-velocity>
                <z-velocity>0.0</z-velocity>
            </velocity>
            <spacing>1.2</spacing>
            <mass>1.0</mass>
            <type>0</type>
            <eps>1.0</eps>
            <sigma>1.2</sigma>
        </cuboid>
        <cuboid>
            <base_coordinates>
                <x-coordinate>0.6</x-coordinate>
                <y-coordinate>27</y-coordinate>
                <z-coordinate>0</z-coordinate>
            </base_coordinates>
            <number_particles>
                <x-number>250</x-number>
                <y-number>20</y-number>
                <z-number>1</z-number>
            </number_particles>
            <velocity>
                <x-velocity>0.0</x-velocity>
                <y-velocity>0.0</y-velocity>
                <z-velocity>0.0</z-velocity>
            </velocity>
            <spacing>1.2</spacing>
            <mass>2.0</mass>
            <type>1</type>
            <eps>1.0</eps>
            <sigma>1.1</sigma>
        </cuboid>
    </Particles>
</Molsim_Input>

=== katarziz/MolSim/input/MembraneSmall.xml
<?xml version="1.0" encoding="UTF-8"?>

<Molsim_Input xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="input.xsd">
    <Parameters>
        <delta_t>0.01</delta_t>
        <t_end>500</t_end>
        <Grav>
            <x-grav>0</x-grav>
            <y-grav>0</y-grav>
            <z-grav>-0.001</z-grav>
        </Grav>
        <container>LinkedCell</container>
        <checkpoint_freq>10000</checkpoint_freq>
        <box_size>
            <x-size>45</x-size>
            <y-size>45</y-size>
            <z-size>45</z-size>
        </box_size>
        <boundary_conditions>
            <top_bound>out</top_bound>
            <right_bound>out</right_bound>
            <bottom_bound>out</bottom_bound>
            <left_bound>out</left_bound>
            <front_bound>ref</front_bound>
            <back_bound>ref</back_bound>
        </boundary_conditions>
        <cutoff>4</cutoff>
        <writer/>
        <force/>
        <output_name>MembraneSmall</output_name>
        <output_frequency>5</output_frequency>
        <statistics_freq>0</statistics_freq>
    </Parameters>
    <ThermostatParams>
        <T_init>0</T_init>
        <T_targ>0</T_targ>
        <f_therm>0</f_therm>
        <delta_T>0</delta_T>
    </ThermostatParams>
    <Particles>
        <membrane>
            <base_coordinates>
                <x-coordinate>15</x-coordinate>
                <y-coordinate>15</y-coordinate>
                <z-coordinate>1.5</z-coordinate>
            </base_coordinates>
            <plane>xy</plane>
            <number_particles>
                <width>10</width>
                <height>10</height>
            </number_particles>
            <velocity>
                <x-velocity>0</x-velocity>
                <y-velocity>0</y-velocity>
                <z-velocity>0</z-velocity>
            </velocity>
            <spacing>2.2</spacing>
            <mass>1.0</mass>
            <type>0</type>
            <eps>1</eps>
            <sigma>1</sigma>
            <r_zero>2.2</r_zero>
            <k>300</k>
            <F_mem>
                <F_up>0.8</F_up>
                <Area>
                    <width_begin>4</width_begin>
                    <width_end>5</width_end>
                    <height_begin>4</height_begin>
                    <height_end>5</height_end>
                </Area>
            </F_mem>
        </membrane>
    </Particles>
    </Molsim_Input>

=== katarziz/MolSim/input/NanoFlowInput.xml
<?xml version="1.0" encoding="UTF-8"?>

<Molsim_Input xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="input.xsd">
    <Parameters>
        <delta_t>0.0005</delta_t>
        <t_end>500</t_end>
        <Grav>
            <x-grav>0</x-grav>
            <y-grav>-0.8</y-grav>
            <z-grav>0.0</z-grav>
        </Grav>
        <container>LinkedCell</container>
        <checkpoint_freq>0</checkpoint_freq>
        <box_size>
            <x-size>30</x-size>
            <y-size>30</y-size>
            <z-size>12</z-size>
        </box_size>
        <boundary_conditions>
            <top_bound>per</top_bound>
            <right_bound>out</right_bound>
            <bottom_bound>per</bottom_bound>
            <left_bound>out</left_bound>
            <front_bound>per</front_bound>
            <back_bound>per</back_bound>
        </boundary_conditions>
        <cutoff>2.75</cutoff>
        <writer/>
        <force/>
        <output_name>NanoFlow</output_name>
        <output_frequency>50</output_frequency>
        <statistics_freq>10000</statistics_freq>
    </Parameters>
    <ThermostatParams>
        <T_init>40</T_init>
        <T_targ>40</T_targ>
        <f_therm>10</f_therm>
        <delta_T>INF</delta_T>
    </ThermostatParams>
    <Particles>
        <cuboid>
            <base_coordinates>
                <x-coordinate>1.0</x-coordinate>
                <y-coordinate>0.5</y-coordinate>
                <z-coordinate>0.5</z-coordinate>
            </base_coordinates>
            <number_particles>
                <x-number>2</x-number>
                <y-number>30</y-number>
                <z-number>12</z-number>
            </number_particles>
            <velocity>
                <x-velocity>0</x-velocity>
                <y-velocity>0</y-velocity>
                <z-velocity>0</z-velocity>
            </velocity>
            <spacing>1.0</spacing>
            <mass>1.0</mass>
            <type>0</type>
            <eps>2.0</eps>
            <sigma>1.1</sigma>
            <fixed>true</fixed>
        </cuboid>
        <cuboid>
            <base_coordinates>
                <x-coordinate>27.2</x-coordinate>
                <y-coordinate>0.5</y-coordinate>
                <z-coordinate>0.5</z-coordinate>
            </base_coordinates>
            <number_particles>
                <x-number>2</x-number>
                <y-number>30</y-number>
                <z-number>12</z-number>
            </number_particles>
            <velocity>
                <x-velocity>0</x-velocity>
                <y-velocity>0</y-velocity>
                <z-velocity>0</z-velocity>
            </velocity>
            <spacing>1.0</spacing>
            <mass>1.0</mass>
            <type>0</type>
            <eps>2.0</eps>
            <sigma>1.1</sigma>
            <fixed>true</fixed>
        </cuboid>
        <cuboid>
            <base_coordinates>
                <x-coordinate>3.2</x-coordinate>
                <y-coordinate>0.6</y-coordinate>
                <z-coordinate>0.6</z-coordinate>
            </base_coordinates>
            <number_particles>
                <x-number>20</x-number>
                <y-number>25</y-number>
                <z-number>10</z-number>
            </number_particles>
            <velocity>
                <x-velocity>0</x-velocity>
                <y-velocity>0</y-velocity>
                <z-velocity>0</z-velocity>
            </velocity>
            <spacing>1.2</spacing>
            <mass>1.0</mass>
            <type>1</type>
            <eps>1.0</eps>
            <sigma>1.0</sigma>
            <fixed>false</fixed>
        </cuboid>
    </Particles>
</Molsim_Input>

=== katarziz/MolSim/test/TestInput/XMLReaderTestInputSingleParticle.xml
<?xml version="1.0" encoding="UTF-8"?>

<Molsim_Input xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation="../../input/input.xsd">
    <Parameters>
        <delta_t>0.002</delta_t>
        <t_end> 1.0 </t_end>
        <grav>0</grav>
        <container>LinkedCell</container>
        <checkpoint_freq>0</checkpoint_freq>
        <box_size>
            <x-size/>
            <y-size/>
            <z-size/>
        </box_size>
        <boundary_conditions>
            <top_bound/>
            <right_bound/>
            <bottom_bound/>
            <left_bound/>
            <front_bound/>
            <back_bound/>
        </boundary_conditions>
        <cutoff/>
        <writer/>
        <force/>
        <output_name/>
        <output_frequency/>
        <statistics_freq>0</statistics_freq>
    </Parameters>
    <ThermostatParams>
        <T_init>0</T_init>
        <T_targ>0</T_targ>
        <f_therm>0</f_therm>
        <delta_T>0</delta_T>
    </ThermostatParams>
    <Particles>
        <particle>
            <position>
                <x-coordinate>0.0</x-coordinate>
                <y-coordinate>5.0</y-coordinate>
                <z-coordinate>0.0</z-coordinate>
            </position>
            <velocity>
                <x-velocity>0.0</x-velocity>
                <y-velocity>-1.0</y-velocity>
                <z-velocity>0.0</z-velocity>
            </velocity>
            <mass>1.0</mass>
            <type>0</type>
            <eps>5</eps>
            <sigma>1</sigma>
            <fixed>false</fixed>
        </particle>
    </Particles>
</Molsim_Input>
